### ISSUE TITLE
Incoming and Unprocessed should show upload-info inline

### ISSUE THREAD

**Issue by dfabulich** [iftechfoundation/ifarchive-admintool#18]
https://upload.ifarchive.org/admin/incoming shows a list of files, each of which have an "(info)" link, linking to the upload metadata.

The archive team uses that metadata to decide what to do with each file, so, to save us all a bunch of clicks, I think this data should be revealed inline directly on the https://upload.ifarchive.org/admin/incoming page.

**Comment by erkyrath** [comment]
Done.

You still have to hit the "(info)" link to add notes. Sorry, that's slightly inconsistent.
