### ISSUE TITLE
Dockerized testing environment

### ISSUE THREAD

**Issue by dfabulich** [iftechfoundation/ifarchive-admintool#19]
> It is possible to test the admin interface on a local Apache server. I have not yet written up the procedure; apologies.

If @erkyrath can provide me some documentation here, I can turn it into a Dockerfile, like we do with https://github.com/iftechfoundation/ifarchive-unbox and https://github.com/iftechfoundation/ifdb

**Comment by erkyrath** [comment]
Yep, I will write up the setup plan.

**Comment by erkyrath** [comment]
This now exists as https://github.com/iftechfoundation/ifarchive-admintool/blob/main/TESTING.md

Fair warning: I haven't tested the Linux test setup plan. It's reconstructed from what I did on the live Archive server; chances are good I forgot a step somewhere. So let me know what doesn't work, and I'll update the document.

**Comment by erkyrath** [comment]
https://github.com/iftechfoundation/ifarchive-admintool/issues/21 is done. This simplifies the test setup by quite a bit.

I've moved some directories around in the test setup, so if you already set up a test environment, you may want to redo it with the current instructions.
