### ISSUE TITLE
Human-readable file sizes

### ISSUE THREAD

**Issue by dougo** [iftechfoundation/ifarchive-admintool#26]
It might be nice to display file sizes using M or G were appropriate instead of only using bytes.

**Comment by erkyrath** [comment]
I like knowing the exact size (and I even wrote a comma-separator function!) Could be a preference though.

**Comment by dougo** [comment]
Good point. Maybe it could show both? Or have a toggle or tooltip or something. Very minor issue.

**Comment by dfabulich** [comment]
For this use case, I think it's valuable to see more digits for larger sizes. It's easy to accidentally fail to notice a G vs. an M, harder to notice that a number contains three commas 1,783,299,936

**Comment by erkyrath** [comment]
Re-bumping this since I wrote a k/M/G formatter for the front page.

The tooltip with exact size seems like the way to go.
