### ISSUE TITLE
Allow users to add notes to upload info

### ISSUE THREAD

**Issue by dfabulich** [iftechfoundation/ifarchive-admintool#32]
> I think we're gonna need a "volunteer notes" field for incoming files, so we can slap on post-its for among ourselves

I could have used this today when deciding what to do with a 674MB incoming file.

**Comment by erkyrath** [comment]
There is now an "Add Note" button on the upload-info page. Hit the "(info)" link to both view and add notes.

There is no "Delete Note" button; right now it's purely additive.
