### ISSUE TITLE
Add tuid to uploads table

### ISSUE THREAD

**Issue by erkyrath** [iftechfoundation/ifarchive-admintool#44]
This comes in via the upload.py script. We'll want to display it as part of the upload info and then pass it back in ifdb_notify.

**Comment by erkyrath** [comment]
This task follows https://github.com/iftechfoundation/ifdb/pull/299 .

**Comment by dfabulich** [comment]
https://github.com/iftechfoundation/ifdb/pull/299 is merged and deployed to ifdb.org now.

**Comment by erkyrath** [comment]
This should be done now, in upload.py and the admin interface.
