### ISSUE TITLE
Can't add notes on files without upload info

### ISSUE THREAD

**Issue by Keltena** [iftechfoundation/ifarchive-admintool#47]
The "Add Note" button only appears for files with upload info.

This is usually fine, but for files added from [the CAAD archive](https://intfiction.org/t/preservacion-de-la-antigua-web-del-caad-enlaces/62294/5)—recent uploads with no upload info which still require extensive review—the ability to make notes would be helpful.

**Comment by erkyrath** [comment]
This should work now.

If you add a note to a file with no upload info, it will show as being uploaded by "Anonymous" with permission "unknown". (Because we had to create an upload record without this data.)
